version: '3.4'

services:
  db:
   environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Password123?
  bazart_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionString=Server=db,1433;Database=BazArtDB;User Id=SA;Password=Password123?;Trusted_Connection=false;Encrypt=False;
      - DaysExpireToken=5
    ports:
     - 5000:80
  bazart_ui:
   ports:
    - 3000:3000